Moves a few i8 to c_char for ARM compatible tensor engine builds (#1814)
Summary:

As title. For the interested, Claude mentions that the C standard says `char` signedness is implementation-defined.

x86_64 for instance has `char` be signed - therefore all of our usage of char as i8 was correct.

But on aarch64, it's unsigned by default.

Without this change, you see a lot of errors like this:

```
      error[E0308]: mismatched types
         --> monarch_rdma/src/rdma_manager_actor.rs:398:57
          |
      398 |                 let pci_addr = std::ffi::CStr::from_ptr(pci_addr_buf.as_ptr())
          |                                ------------------------ ^^^^^^^^^^^^^^^^^^^^^ expected `*const u8`, found `*const i8`
          |                                |
          |                                arguments to this function are incorrect
          |
          = note: expected raw pointer `*const u8`
                     found raw pointer `*const i8`
      note: associated function defined here
```

Differential Revision: D86711698