Disable test_setup in Github CI (#1752)
Summary:

In Github actions, this test fails like so:
```
FAILED python/tests/test_python_actors.py::test_setup - ValueError: error spawning proc mesh: statuses: Timeout(30.000905376s)=0..1
```
however, in internal testing it passes multiple stress tests.
Disable for now to recover green CI, and investigate the cause in the background.
(not reverting the introduction of this test since it does pass internally).

Reviewed By: colin2328

Differential Revision: D86225773