Include executed command in ProcStatus error messages
Summary:
mast job `ifm_video_grpo-vf4q2f2s` failed with:

> ValueError: error creating proc (host rank 0) on host mesh agent metatls:twshared0965.01.zch2.facebook.com:26600,service,host_agent[0]<hyperactor_mesh::host_mesh::host_agent::HostAgent>, state: {"name":"policy_mesh_procs_1-1ANkrajLR8yq","status":{"Failed":"proc 'metatls:twshared0965.01.zch2.facebook.com:26600,policy_mesh_procs_1-1ANkrajLR8yq' failed to configure process: Ready(Terminal(Stopped { exit_code: 127, stderr_tail: [] }))"},"state":null,"generation":0,"timestamp":{"secs_since_epoch":1775583773,"nanos_since_epoch":15028409}}

exit code 127 should mean command not found, but there is no log helping us understand what command was used.

This diff adds a field to `ProcStatus` so this information can be returned and logged.

Differential Revision: D100021246