Remove deprecated await on proc_mesh/spawn calls in examples (#1406)
Summary:

Fix Monarch examples broken by removal of DeprecatedNotAFuture in D82835567.

D82835567 removed the `DeprecatedNotAFuture` compatibility shim that provided fake `__await__()` methods on `ProcMesh` and `ActorMesh` objects.

With the shim removal, these examples started failing with:
```
TypeError: object ActorMesh can't be used in 'await' expression
```

This diff removes the incorrect `await` keywords.

Reviewed By: dulinriley

Differential Revision: D83138346