Turn on tokio time features for monarch_tensor_worker::stream tests
Summary:
Fixing test breakages like:
```
thread 'worker-stream' panicked at fbcode/monarch/hyperactor/src/clock.rs:293:9:
A Tokio 1.x context was found, but timers are disabled. Call `enable_time` on the runtime builder to enable timers.
```
in stream.rs
This was caused by a new usage of `tokio::time::timeout` via `RealClock.timeout`. But
we use this in many places and i

Reviewed By: colin2328

Differential Revision: D87099251